defaults:
  - override hydra/sweeper: optuna          # https://hydra.cc/docs/plugins/optuna_sweeper/
  - override hydra/sweeper/sampler: tpe

hydra:
  run:
    dir: .
  output_subdir: null
  sweeper:
    sampler:
      seed: 42
    direction: maximize    # [options: minimize, maximize]
    study_name:  deeplabv3
    storage: sqlite:///deeplabv3_trials.db
    n_trials: 30
    n_jobs: 1
    params:
      optimizer.lr: tag(log, interval(1e-4, 1e-1))
      optimizer.weight_decay: tag(log, interval(1e-10, 3e-1))

experiment_name: experiment_1
optimize_metric: accuracy   # [options: accuracy, val_loss, miou, mcc, train_loss] change direction config (above) accordingly. also used for early stopping

data:     # images and labels files should have the same filename
  train:
    image_path: /home/avnish/backup/data/swimseg/A/train/
    label_path: /home/avnish/backup/data/swimseg/B/train/
  val:
    image_path: /home/avnish/backup/data/swimseg/A/val/
    label_path: /home/avnish/backup/data/swimseg/B/val/

base_transform:     # applicabel to all datasets.  remove _target_ and subsequent params for no base transforms
  _target_: torchvision.transforms.Resize
  size: [64, 64]
  interpolation: NEAREST

train_transform:    # remove _target_ and subsequent params for no train transforms
  _target_: utils.rand_augment.RandAugment
  n: 4
  m: 15

train_params:
  batch_size: 32
  max_epochs: 5
  enable_early_stopping: True

model_params:
  checkpoint:             # add checkpoint to resuming training
  model:
    _target_: torchvision.models.segmentation.deeplabv3_resnet50    # deeplabv3_mobilenet_v3_large, lraspp_mobilenet_v3_large
    progress: True
    num_classes: 3  # including background class
    weights_backbone:
    weights:

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 0.0

criterion:
  _target_: torch.nn.CrossEntropyLoss

early_stopping:
  _target_: utils.model.EarlyStopping
  patience: 10
  delta: 0

evaluate:
  image_path: /home/avnish/backup/data/swimseg/A/test/
  label_path: /home/avnish/backup/data/swimseg/B/test/
  batch_size: 32
  model_path: /home/avnish/SkyCloudAugmentation/deeplabv3/experiments/experiment_1/models/model_epoch_4.pth